name: Pull Request
run-name: Pull request ${{ github.ref }} opened
on:
  push:
jobs:
  Pull-Request-On-Main:
    runs-on: ubuntu-latest
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - run: echo "Running a job due to pull request ${{ github.ref }}"
      - run: echo "Job was triggered due to a ${{ github.event_name }} event."
      - run: echo "The triggering branch was ${{ github.head_ref }} pulling to ${{ github.base_ref }}."
      - name: 'Pull code'
        uses: 'actions/checkout@v4'
      - name: 'Authenticate with Google'
        uses: 'google-github-actions/auth@v2'
        id: 'gcpauth'
        with:
          project_id: 'experiments-459907'
          workload_identity_provider: 'projects/966464862995/locations/global/workloadIdentityPools/github-actions/providers/github-oidc'
      - name: List repository location
        run: echo "${{ github.workspace }}"
      - name: List files in repository
        run: ls ${{ github.workspace }}
      - name: 'Echo creds'
        run: cat ${{ steps.gcpauth.outputs.credentials_file_path }}
      - name: 'Print OIDC Token'
        run: |
          echo "Retrieving OIDC Token..."
          TOKEN=$(curl -s -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r .value)
          echo "OIDC Token: $TOKEN"
          echo "Decoded Token:"
          echo $TOKEN | cut -d '.' -f2 | base64 --decode | jq .
      - name: 'Get Secrets'
        id: 'gcsm'  # Google Cloud Secret Manager
        uses: 'google-github-actions/get-secretmanager-secrets@v2'
        with:
          secrets: |-
            s1:966464862995/secret-val
            s2:966464862995/another-secret
      - name: 'Echo Secrets'
        run: echo "s1=${{ steps.gcsm.outputs.s1 }}, s2=${{ steps.gcsm.outputs.s2 }}"

