name: RabbitMQ
run-name: Publish RabbitMQ Service
on:
  push:
    # Run this on push to staging or main, since any push MUST be a PR merge
    # or require immediate deployment
    branches:
      - staging
      - main
    paths:
      - services/rabbitmq/**
      - shared/**
      - .github/workflows/rabbitmq.yml
env:
  GCP_PROJECT_ID: 'experiments-459907'
  GCP_WORKLOAD_IDENTITY_PROVIDER: 'projects/966464862995/locations/global/workloadIdentityPools/github-actions/providers/github-oidc'
  GCP_ARTIFACT_REGISTRY_LOCATION: 'europe-west4'
  GCP_ARTIFACT_REGISTRY_REPOSITORY: 'actions-playground'
  SERVICE_NAME: 'rabbitmq'
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ env.GCP_WORKLOAD_IDENTITY_PROVIDER }}

      - name: Determine image tag
        id: set-tag
        run: |
          if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/heads/staging" ]]; then
            echo "tag=staging" >> "$GITHUB_OUTPUT"
          else
            echo "tag=latest" >> "$GITHUB_OUTPUT"
          fi

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.GCP_ARTIFACT_REGISTRY_LOCATION }}-docker.pkg.dev

      - name: Build Docker image for publishing
        run: |
          docker build \
            --tag ${{ env.GCP_ARTIFACT_REGISTRY_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_ARTIFACT_REGISTRY_REPOSITORY }}/${{ env.SERVICE_NAME }}:${{ steps.set-tag.outputs.tag }} \
            --file ${{ github.workspace }}/services/${{ env.SERVICE_NAME }}/Dockerfile \
            ${{ github.workspace }}/services/${{ env.SERVICE_NAME }}

      - name: Push Docker image to Artifact Registry
        run: |
          docker push \
            ${{ env.GCP_ARTIFACT_REGISTRY_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_ARTIFACT_REGISTRY_REPOSITORY }}/${{ env.SERVICE_NAME }}:${{ steps.set-tag.outputs.tag }}